hook.Add("PopulateToolMenu", "ArmorKill", function()
    spawnmenu.AddToolMenuOption("Utilities", "lemontine", "ArmorKill", "Armor on Kill", "", "", function(panel)
        panel:ClearControls()
        if LocalPlayer():IsAdmin() or LocalPlayer():IsSuperAdmin() or game.SinglePlayer() then
            panel:Help("Server options")
            panel:CheckBox("Enable Armor on Kill", "armorkill_enabled")
            panel:CheckBox("Only headshots give armor?", "armorkill_headshots_only")
            panel:CheckBox("Should one-shots be counted as headshots?", "armorkill_overkills_are_headshots")
            panel:ControlHelp("")
            panel:NumSlider("Max armor", "armorkill_max", 0, 100, 0)
            panel:ControlHelp("Limits the armor replenishable by a kill")
            panel:NumSlider("Armor per kill", "armorkill_multiplier", 0, 10, 1)
            panel:ControlHelp("Number of armor pickups to reward on kill")
            panel:ControlHelp("")
            panel:NumSlider("Armor chance", "armorkill_chance", 0, 100, 2)
            panel:ControlHelp("The chance as a % that the kill gives armor")
        end
        panel:Help("Client options")
        panel:CheckBox("Mute armor on kill", "armorkill_mute")
        panel:Help("(Made by lemontine)")
    end)
end)